title: Run Like Hell 2016
details:
  when: 7:30pm Friday, October 28, 2016
  where: 3614 Woodburn Ave.
  map_url: http://www.gmap-pedometer.com/?r=6642580
cff:
  address: Cystic Fibrosis Foundation, 4420 Carver Woods Drive, Cincinnati, OH 45242
  email: cincinnati@cff.org
contact:
  name: Laura Morgan
  email: lmorgan@cff.org
  phone: 513-533-9300
  phone_ext: 12

# TODO Update these values when we switch to TLD.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://cincyrunlikehell.com" # the base hostname & protocol for your site

# Build settings
markdown: kramdown
sass:
  style: compressed
gems:
 - jekyll-coffeescript

exclude: ['vendor']
