title: Run Like Hell 2016
cff:
  address: Cystic Fibrosis Foundation, 4420 Carver Woods Drive, Cincinnati, OH 45242
  email: cincinnati@cff.org
contact:
  name: Laura Morgan
  email: lmorgan@cff.org
  phone: 513-533-9300
  phone_ext: 12
baseurl: "/cincyrunlikehell-com" # the subpath of your site, e.g. /blog
url: "https://ample.github.io" # the base hostname & protocol for your site

# Build settings
markdown: kramdown
sass:
  style: compressed
gems:
 - jekyll-coffeescript
